import json
from typing import Optional, Dict, Any
from core.debate.registry import BaseDebateParticipant
from core.debate.schema import MessageType

class ResearcherAgent(BaseDebateParticipant):
    """
    Agent responsible for introducing Claims and providing Evidence.
    """
    def __init__(self, agent_id: str = "Researcher_01"):
        super().__init__(agent_id)
        self.system_prompt: str = (
            "You are a strict Researcher agent in a formal debate. "
            "You must return ONLY valid JSON matching the DebateMessage Pydantic schema. "
            "Do not include natural language prose before or after the JSON. "
            "Valid message types for you are usually CLAIM, EVIDENCE, or CONCEDE."
        )

    def generate_response(self, error_hint: Optional[str] = None, context: Optional[str] = None) -> str:
        """
        Generates a JSON response representing the agent's action.
        Includes LLM prompting strategy ensuring strict JSON structure.
        """
        prompt: str = self.system_prompt
        if context:
            prompt += f"\nContext: {context}"
        if error_hint:
            prompt += f"\nPREVIOUS ERROR - FIX SCHEMA OR YOU WILL BE TERMINATED: {error_hint}"
            
        # In actual implementation: mock_response_str = llm_client.generate(prompt)
        
        # Simulating an LLM returning valid JSON
        mock_response: Dict[str, Any] = {
            "debate_id": "TBD_by_engine",
            "agent_id": self.agent_id,
            "message_type": MessageType.CLAIM.value,
            "content": "A simulated claim generated by the Researcher based on graph extraction.",
            "references": [],
            "metadata": {}
        }
        return json.dumps(mock_response)

class CriticAgent(BaseDebateParticipant):
    """
    Agent responsible for challenging Claims and introducing Rebuttals.
    """
    def __init__(self, agent_id: str = "Critic_01"):
        super().__init__(agent_id)
        self.system_prompt: str = (
            "You are a strict Critic agent in a formal debate. "
            "You must return ONLY valid JSON matching the DebateMessage Pydantic schema. "
            "Do not include natural language prose before or after the JSON. "
            "Valid message types for you are usually CHALLENGE, REBUTTAL, or CONCEDE."
        )

    def generate_response(self, error_hint: Optional[str] = None, context: Optional[str] = None) -> str:
        prompt: str = self.system_prompt
        if context:
            prompt += f"\nContext: {context}"
        if error_hint:
            prompt += f"\nPREVIOUS ERROR - FIX SCHEMA OR YOU WILL BE TERMINATED: {error_hint}"
            
        mock_response: Dict[str, Any] = {
            "debate_id": "TBD_by_engine",
            "agent_id": self.agent_id,
            "message_type": MessageType.CHALLENGE.value,
            "content": "A simulated challenge generated by the Critic against the prior claim.",
            "references": [],
            "metadata": {}
        }
        return json.dumps(mock_response)

class SynthesizerAgent(BaseDebateParticipant):
    """
    Agent responsible for resolving the debate into a final claim, ready to hook_into_graph.
    """
    def __init__(self, agent_id: str = "Synthesizer_01"):
        super().__init__(agent_id)
        self.system_prompt: str = (
            "You are a Synthesizer agent in a formal debate. "
            "Your job is to read the debate session, resolve conflicts, and formulate a final claim. "
            "You must return ONLY valid JSON matching the DebateMessage Pydantic schema. "
            "Your message type is typically CLAIM (the final agreed fact) or ESCALATE (if unresolvable)."
        )

    def generate_response(self, error_hint: Optional[str] = None, context: Optional[str] = None) -> str:
        prompt: str = self.system_prompt
        if context:
            prompt += f"\nContext: {context}"
        if error_hint:
            prompt += f"\nPREVIOUS ERROR - FIX SCHEMA OR YOU WILL BE TERMINATED: {error_hint}"
            
        mock_response: Dict[str, Any] = {
            "debate_id": "TBD_by_engine",
            "agent_id": self.agent_id,
            "message_type": MessageType.CLAIM.value,
            "content": "A synthesized final claim resolving the debate conflicts.",
            "references": [],
            "metadata": {"synthesis_complete": True}
        }
        return json.dumps(mock_response)
